### ISSUE TITLE
Lastname input field does not allow specific chars like "ß"

### ISSUE THREAD

**Issue by kreidewe** [wmdbsystems/WMDB.Forger#15]
In the registration process, typing in "ß", leads to a message, that this input is not allowed. Firstname and lastname should allow UTF-8 chars.

**Comment by wmdbMattes** [comment]
Which registration are you referring to?

**Comment by NeoBlack** [comment]
german umlauts also not supported, e.g. in profile form

**Comment by wmdbMattes** [comment]
Wrong Project :)
