### ISSUE TITLE
add ifferent Cycle Time View

### ISSUE THREAD

**Issue by robert-weissgraeber** [wmdbsystems/WMDB.Forger#2]
to resolve the question "when might my ticket be solved (cycle time)" the view should consider the time when the ticket was openend, not when it was closed for the x axis.

**Comment by wmdbMattes** [comment]
I don't get that request.
Cycle Time is currently being calculated as follows:
`Date opened - Date resolved`

**Comment by wmdbMattes** [comment]
Any more feedback? :)

**Comment by robert-weissgraeber** [comment]
Yes, will do. will take some time, though, can be closed for `now`.
