### ISSUE TITLE
Inserting special chars into search causes 500

### ISSUE THREAD

**Issue by maddy2101** [wmdbsystems/WMDB.Forger#35]
I searched today for a search string like *mapping at property path "":Object with* (tried with and without quotation marks around) and got a 500 Internal Server Error message from Flow. Is this avoidable?

**Comment by wmdbMattes** [comment]
can you try to post in a codeblock what you actually searched for?
Or even better: provide a link?

**Comment by maddy2101** [comment]
[code]https://forger.typo3.org/standard/search?query=mapping+at+property+path+%22%22%3AObject+with[code]

**Comment by maddy2101** [comment]
thanks a bunch *bow*
