### ISSUE TITLE
changing links

### ISSUE THREAD

**Issue by RolandReichenauer** [wmdbsystems/WMDB.Forger#4]
Dear Sirs,

two days ago we changed our TYPO3 to version 6.2.11 and we recognized a special behavior:
Trying to change an existing data-link (class=”download”) the dialog roots me to file card “Externe URL” an not to “Datei”. All further versions up to 6.2.10 the change dialog run correct and I saw a button “Aktualisieren” for confirmation my change. When I leave file card “Externe URL” in change mode and choose explicitly file card “Datei” this button is missing. I think all other types of links such as “Seite”, “Ordner”, “Email”, etc. will run correctly.
Did I detect a bug? Please give me feedback!

Yours sincerely – Roland Reichenauer

**Comment by wmdbMattes** [comment]
Hi Roland,

I did not have the time yet to dig into the issue, but at least I can tell you that you picked the wrong project :)

You can find the bugtracker of the TYPO3 CMS project here https://forge.typo3.org/projects/typo3cms-core

I will close this issue here, ok?

Cheers
Mathias
