### ISSUE TITLE
the abscissa / ordinate cursor for the widgets in home page does not work

### ISSUE THREAD

**Issue by erredeco** [wmdbsystems/WMDB.Forger#45]
the abscissa / ordinate cursor for the widgets in home page does not work in chrome and firefox (desktop edition) ("Gerrit overview" works), it works on chrome for tablets.

chrome console logs:
Failed to load resource: net::ERR_INSECURE_RESPONSE https://analytics.wmdb.de/piwik.js

**Comment by wmdbMattes** [comment]
fixed

**Comment by erredeco** [comment]
ummm I don't see differences :S also, does not work with IE10

**Comment by wmdbMattes** [comment]
the certificate for https://analytics.wmdb.de was out of date and has been fixed.
Apart from that maybe I don't get what you are referring to?

**Comment by erredeco** [comment]
![cattura](https://cloud.githubusercontent.com/assets/3647646/8081994/1599a27a-0f7a-11e5-90f5-5063a459b7fd.png)

Oh, sorry. I mean the functionality highlighted in the attached picture. I remember it used to work for example for "Opened vs. Closed" graph

**Comment by wmdbMattes** [comment]
does it work on the Forge Velocity Graph?
I wonder if maybe the Library isn't capable of rendering more than one of those cursors at once

**Comment by erredeco** [comment]
As I said it works only for gerrit overview graph...but I remember they all worked together :S or am I wrong?

**Comment by wmdbMattes** [comment]
variable hickups in JS. Will be fixed with next rollout

**Comment by wmdbMattes** [comment]
Please force-reload the JS file

**Comment by erredeco** [comment]
hickup has gone away :)
