### ISSUE TITLE
Different count for open reviews

### ISSUE THREAD

**Issue by michadu** [wmdbsystems/WMDB.Forger#54]
On the start page is shown:
Open Reviews: 305

Selecting Gerrit->All shows:
Showing hits 1 to 25 of 259

305 <--> 259
Both informations should show the same count of open reviews.

**Comment by wmdbMattes** [comment]
This is because the Gerrit Views *exclude* WIP patchsets.
Do you have any idea where to put this information aside from the Help screen?

**Comment by michadu** [comment]
On the start screen you could write
Open Reviews: 305 (including 46 WIP)

Or in the Gerrit Menu you add a Link for "All (incl. WIP)"
