### ISSUE TITLE
Search > paginated results don't hold the "search closed ticket" check

### ISSUE THREAD

**Issue by erredeco** [wmdbsystems/WMDB.Forger#62]
Steps to reproduce: 
1) go to the "search results" page (e.g. search for something on the home page)
2) check "Search closed Tickets" and hit search (e.g. "Content")
3) the paginated results appear
4) click on page "2" of the results
Result:
The page 2 of results show only the results without "search closed tickets" (which has been unchecked, if I check it again and press search, I will return to page 1)

**Comment by erredeco** [comment]
...seems not solved yet...

**Comment by wmdbMattes** [comment]
it was solved, but not yet rolled out.
I rolled it out now
